
// This file is automatically generated. Do not edit manually.
import Foundation

struct Secrets {
    static let openAIKey: String = "${OPENAI_API_KEY}"
    static let pineconeKey: String = "${PINECONE_API_KEY}"
    static let pineconeHost: String = "${PINECONE_HOST}"
    static let archiveCooke: String = "${ARCHIVE_COOKIE}"
}
